
services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    container_name: doc_postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - doc_network
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # 2. AUTH SERVICE
  auth-service:
    build:
      context: ./services/auth-service
    container_name: doc_auth_service
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      JWT_SECRET_KEY: super-secret-key
    depends_on:
      - postgres
    networks:
      - doc_network

networks:
  doc_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
